# These are supported funding model platforms

github: @AzeMusic
patreon: @AzeMusic
open_collective: @AzeMusic
ko_fi: @AzeMusic
tidelift: npm/ledy
community_bridge: ledy-cloud
liberapay: @ledy
issuehunt:  @AzeMusic
otechie:  @AzeMusic
lfx_crowdfunding: ledy-cloud
custom: https://t.me/ledyplaylist
