services:
  - type: web
    plan: free
    name: LedyMusicBot
    env: python
    buildCommand: pip3 install --no-cache-dir -U -r requirements.txt
    startCommand: /bin/sh -c python3\ main.py
    repo: https://github.com/tecnoagateam/LedyMusicBot.git      
    branch: web
    envVars:
      - key: BOT_TOKEN 
        sync: false      
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: SESSION_NAME 
        sync: false    
      - key: PYTHON_VERSION
        sync: false 
      - key: SUDO_USERS
        sync: false
      - key: BOT_OWNER  
        sync: false
      - key: DURATION_LIMIT
        sync: false
      - key: PMPERMIT  
        sync: false
      - key: COMMAND_PREFIXES
        sync: false
      - key: BOT_NAME  
        sync: false
      - key: BOT_USERNAME
        sync: false       
    autoDeploy: false
