services:
  - type: web
    plan: free
    name: LedyMusicBot
    env: python
    FROM: nikolaik/python-nodejs:python3.10-nodejs17
    RUN: apt update && apt upgrade -y
    RUN: apt install ffmpeg -y
    COPY: . /app
    WORKDIR: /app
    RUN: chmod 777 /app
    RUN: pip3 install --upgrade pip
    RUN: pip3 install --no-cache-dir -U -r requirements.txt
    startCommand: /bin/sh -c python3\ main.py
    repo: https://github.com/tecnoagateam/LedyMusicBot.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: SESSİON_NAME 
        sync: false    
    autoDeploy: false
