services:
  - type: worker
    plan: free
    name: LedyMusicBot
    env: python
    buildCommand: Dockerfile
    startCommand: python3 main.py
    repo: https://github.com/tecnoagateam/LedyMusicBot.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: SESSION_NAME 
        sync: false    
    autoDeploy: false
